driver: torch
device: cpu

workdir:

distributed:
  backend: nccl
  type: single  # single or multiple
  nproc_per_node: 1
  single:
    init_method: tcp://127.0.0.1:23456

transforms:

datasets:

models:

solvers:

io:

build:

options:

flow:
