driver: torch
device: "cuda"
workdir: /tmp/dist/sam
snapshot: 0
epochs: 1

distributed:
  backend: nccl
  type: single  # single or multiple
  nproc_per_node: 4
  single:
    init_method: tcp://127.0.0.1:23456

transforms:
  train:
    engine: 'torchvision.transforms'
    augs:
      # ToTensor:
      # Resize:
      #   size: [1024, 1024]
      # Normalize:
      #   mean: [0.485, 0.456, 0.406]
      #   std: [0.229, 0.224, 0.225]

datasets:
  dataloader:
    batch_size: 2
    num_workers: 4
    shuffle: False
  coco:
    train:
      root: "/root/krishneel/Downloads/datasets/coco/val2017"
      annFile: "/root/krishneel/Downloads/datasets/coco/annotations/instances_val2017.json"
    val:

models:
  sam:
    name: "vit_h"    
    weights: "/root/krishneel/Documents/research/zero_shot/segment-anything/weights/sam_vit_h_4b8939.pth"

solvers:
  engine: 'torch.optim'
  SGD:
    lr: 0.001
    momentum: 0.9

io:
  engine: 's3_writer'
  args:
    bucket_name: 'sr-shokunin'
    root: 'perception/sam/coco/val2017/features'
  
build:
  model: "sam"
  dataset: "coco"
  solver: "SGD"
  func: "sam_image_feature_saver"
