driver: "../mnist.py"
device: "cuda"

workdir:
  path: "/tmp/dist/mnist"

transforms:
  train: &trans
    engine: "torchvision.transforms"
    ToTensor:
    Normalize:
      mean: [0.1307]
      std: [0.3081]
  val:
    <<: *trans

datasets:
  dataloader:
    batch_size: 128
    num_workers: 4
    collate_fn: 'mnist_collate_fn'
  mnist:
    val:
      root: '/root/krishneel/Downloads/'
      train: False
      download: True
    train:
      root: '/root/krishneel/Downloads/'
      train: True
      download: True

models:
  mnist:

solvers:
  # engine: "torch.optim"
  snapshot: 10000
  SGD:
    lr: 0.01
    momentum: 0.5
  schedulers:
    StepLR:
      step_size: 20
      gamma: 0.1

io:
  # checkpoint:
  #   engine: 's3_writer'
  #   bucket_name: "sr-shokunin"
  #   root: "perception/models/example/mnist/"
  checkpoint:
    engine: 'file_writer'
    root: "/root/krishneel/Downloads/mnist/models/mnist/"

  log_handler:
    engine: 'fair'
    attach:
      every: 10

build:
  mnist:
    dataset: "mnist"
    train:
      solver: "SGD"
      scheduler: "StepLR"
      epochs: 10
      func: "default"
      transforms: "train"
      event_handlers:
        default_checkpoint_handler:
          event_type: EPOCH_COMPLETED
          root: /tmp/weights/
          prefix: mnist_

    val:
      epoch: 1
      # step: 256
      metric: "accuracy"
      transforms: "val"

  model: "mnist"

options:
  train: True
  eval: True

flow:
  - mnist
#   - mnist
