driver: torch
device: "cuda"

workdir:
  path: "/tmp/dist/sam"

distributed:
  backend: nccl
  type: single  # single or multiple
  nproc_per_node: 4
  single:
    init_method: tcp://127.0.0.1:23456

transforms:
  train:
    engine: 'torchvision.transforms'
    # ToTensor:
    # Resize:
    #   size: [1024, 1024]
    # Normalize:
    #   mean: [0.485, 0.456, 0.406]
    #   std: [0.229, 0.224, 0.225]

datasets:
  dataloader:
    batch_size: 8
    num_workers: 8
    shuffle: False
  coco:
    train:
      root: "/root/krishneel/Downloads/datasets/coco/train2017"
      annFile: "/root/krishneel/Downloads/datasets/coco/annotations/instances_train2017.json"
    val:
      root: "/root/krishneel/Downloads/datasets/coco/val2017"
      annFile: "/root/krishneel/Downloads/datasets/coco/annotations/instances_val2017.json"
models:
  sam:
    name: "vit_h"    
    checkpoint: "/root/krishneel/Documents/research/zero_shot/segment-anything/weights/sam_vit_h_4b8939.pth"

solvers:
  engine: 'torch.optim'
  SGD:
    lr: 0.001
    momentum: 0.9

io:
  s3_writer:
    engine: 's3_writer'
    bucket_name: 'sr-shokunin'
    root: 'perception/sam/coco/train2017/features'

build:
  sam:
    dataset: "coco"
    train:
      solver: "SGD"
      epochs: 1
      func: "sam_image_feature_saver"

  model: "sam"
