driver: torch
device: "cuda"
workdir: &workdir /tmp/dist/sam
snapshot: 5000
epochs: 100

distributed:
  backend: nccl
  type: single  # single or multiple
  nproc_per_node: 4
  single:
    init_method: tcp://127.0.0.1:23456

models:
  swin:
    name: "swin"
    pretrained: False
    in_size: &size [896, 896]
    
transforms:
  train:
    engine: "torchvision.transforms"
    augs:
      ToTensor:
      Resize:
        size: *size
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

datasets:
  dataloader:
    batch_size: 2
    num_workers: 4
    shuffle: True
    pin_memory: True
    collate_fn: "collate_data"
  coco:
    # train:
    #   bucket_name: "sr-shokunin"
    #   root: "/root/krishneel/Downloads/datasets/coco/train2017"
    #   anno_fn: "perception/datasets/coco/annotations/instances_train2017.json"
    val:
    train:
      bucket_name: "sr-shokunin"
      root: "perception/datasets/coco/val2017"
      anno_fn: "perception/datasets/coco/annotations/instances_val2017.json"

solvers:
  engine: "torch.optim"
  SGD:
    lr: 0.001
    momentum: 0.9
  schedulers:
    StepLR:
      step_size: 20
      gamma: 0.1

# io:
#   engine: 'summary_writer'
#   args:
#     log_dir: *workdir
  
build:
  model: "swin"
  dataset: "coco"
  solver: "SGD"
  scheduler: "StepLR"  
