driver: torch
device: "cuda"
workdir: /tmp/dist/sam
snapshot: 5000
epochs: 100

distributed:
  backend: nccl
  type: single  # single or multiple
  nproc_per_node: 1
  single:
    init_method: tcp://127.0.0.1:23456

transforms:
  train:
    engine: "torchvision.transforms"
    augs:
      ToTensor:
      Resize:
        size: [1024, 1024]
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

datasets:
  dataloader:
    batch_size: 2
    num_workers: 4
    shuffle: False
  coco:
    # train:
    #   bucket_name: "sr-shokunin"
    #   root: "/root/krishneel/Downloads/datasets/coco/train2017"
    #   anno_fn: "perception/datasets/coco/annotations/instances_train2017.json"
    val:
    train:
      bucket_name: "sr-shokunin"
      root: "perception/datasets/coco/val2017"
      anno_fn: "perception/datasets/coco/annotations/instances_val2017.json"

models:
  swin:
    name: "swin"
    pretrained: False
    in_size: [896, 896]

solvers:
  engine: "torch.optim"
  SGD:
    lr: 0.001
    momentum: 0.9

# io:
#   engine: 's3_writer'
#   args:
#     bucket_name: 'sr-shokunin'
#     root: 'perception/sam/coco/val2017/features'
  
build:
  model: "swin"
  dataset: "coco"
  solver: "SGD"
  func: "update_model"
