driver: torch
device: "cuda"

workdir:
  path: "/tmp/dist/distill"
  unique: False

distributed:
  backend: nccl
  type: single  # single or multiple
  nproc_per_node: 4
  single:
    init_method: tcp://127.0.0.1:23456

models:
  swin:
    in_size: &size [896, 896]
    
transforms:
  train: &train
    engine: "torchvision.transforms"
    augs:
      ToTensor:
      Resize:
        size: *size
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  val:
    <<: *train

datasets:
  dataloader:
    batch_size: 28
    num_workers: 16
    shuffle: True
    pin_memory: True
    collate_fn: "collate_data"
  coco:
    train:
      bucket_name: &bucket "sr-shokunin"
      root: "perception/datasets/coco/train2017"
      anno_fn: "perception/datasets/coco/annotations/instances_train2017.json"    
    val:
      bucket_name: "sr-shokunin"
      root: "perception/datasets/coco/val2017"
      anno_fn: "perception/datasets/coco/annotations/instances_val2017.json"      

solvers:
  engine: "torch.optim"
  snapshot: 5000

  SGD:
    lr: 0.001
    momentum: 0.5
  schedulers:
    StepLR:
      step_size: 8
      gamma: 0.1

io:
  checkpoint:    
    engine: 's3_writer'
    bucket_name: *bucket
    root: "perception/models/sam_distill/"

build:
  swin:
    dataset: "coco"    
    train:
      solver: "SGD"
      scheduler: "StepLR"
      epochs: 100
    val:
      epoch: 1
      step: 50
      # metric: "accuracy"

  model: "swin"
