name: Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DEBIAN_FRONTEND: noninteractive
  REPO_NAME: ${{ github.event.repository.name }}
  PYTHON: "3.10"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.actor }}-${{ github.ref }}-igniter
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_NAME }}
          submodules: true
          clean: true

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON }}

      - name: Running pre-commit
        run: |
          cd ${{ env.REPO_NAME }}
          pip install pre-commit
          pre-commit run --all-files --show-diff-on-failure
